language: rust
sudo: false
dist: trusty
cache: cargo

rust:
  - nightly
  - beta
  - stable

env:
  matrix:
    - FEATURES='' # default ones
    - FEATURES='--features "regexp"'
    - FEATURES='--features "regexp regexp_macros"'
    - FEATURES='--features "stream regexp regexp_macros"'
    - FEATURES='--features "stream regexp regexp_macros" --no-default-features'

matrix:
  include:
    - rust: nightly
      env: FEATURES='--features "nightly regexp"'

    - rust: stable
      env: DOC_FEATURES='--features "std stream regexp regexp_macros" --no-default-features'
      script: eval cargo doc --verbose $DOC_FEATURES

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9c035a194ac4fd4cc061
    on_success: change
    on_failure: always
    on_start: false


addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

before_script: |
  cargo install cargo-travis --force && export PATH=$HOME/.cargo/bin:$PATH

script:
  - eval cargo build --verbose $FEATURES
  - eval cargo test --verbose $FEATURES

after_success: |
  case "$TRAVIS_RUST_VERSION" in
    nightly)
      cargo bench --verbose
      cargo coveralls --verbose
      cargo bench --verbose
      if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" != "master" ]; then
        cargo install cargo-benchcmp --force
        cargo bench > benches-variable
        git fetch
        git checkout master
        cargo bench > benches-control
        cargo benchcmp benches-control benches-variable
      fi
      ;;
    *)
      cargo coveralls --verbose
      ;;
  esac
