[package]

name = "nom"
version = "0.3.11"
authors = [ "contact@geoffroycouprie.com" ]
description = "A byte oriented, zero copy, parser combinators library"
license = "MIT"
repository = "https://github.com/Geal/nom"
readme = "README.md"
documentation = "http://rust.unhandledexpression.com/nom/"
keywords = ["parser", "parser-combinators", "parsing", "streaming", "bit"]

[features]
core = []
nightly = []
