[package]

name = "nom"
version = "0.1.6"
authors = [ "contact@geoffroycouprie.com" ]
description = "A byte oriented, zero copy, parser combinators library"
license = "MIT"
repository = "https://github.com/Geal/nom"
